## OpenCV - Part 5

- Region Mask
- Range Thresholding
- Shape Detection (Hough Transform)

In [2]:
import cv2
import numpy as np
import math

## Region Mask

- Highly useful while extracting any part of the image, defining and working with **non-rectangular ROI** (region of interest). <br>
  <img src="resource/sample_mask.png" style="width:500px; margin-top:10px"></img>
- Region Mask on image is user **Bitwise Operation** (AND, OR, NOT, and XOR operation).
<img src="resource/bitwise_operator.jpg" style="width:500px; margin-top:10px"></img>
- Method :
    - `cv2.bitwise_not(img1, mask)`
    - `cv2.bitwise_and(img1, img2, mask)`
    - `cv2.bitwise_or(img1, img2, mask)`
    - `cv2.bitwise_xor(img1, img2, mask)`
- with parameter :
    - `img1` : input image 1
    - `img2` : input image 2
    - `mask` : optional operation mask, **8-bit single channel** array, that specifies **elements of the output array to be changed**. <br>
    <img src="resource/mask_hand.png" style="width:200px; margin-top:10px"></img>
    

#### Bitwise Not
- Bitwise not dalam python menggunakan operator `~`
- Misal pixel value $200_{10} = 11001000_2$, 
- Jika diterapkan bitwise not pada pixel tersebut, maka akn dihasilkan nilai pixel baru $00110111_2=55_{10}$

```
11001000
-------- ~
00110111
```

In [92]:
a = np.array([200]).astype(np.uint8)
print (~a)

[55]


In [93]:
cv2.bitwise_not(a)

array([[55]], dtype=uint8)

- Bitwise not untuk mask lingkaran putih

In [100]:
img = cv2.imread("lena.jpg")
h, w, c = img.shape

mask = np.zeros((h, w)).astype(np.uint8)
cv2.circle(mask, (h//2, w//2), 100, (255, 255,  255), -1)

mask_inv = cv2.bitwise_not(img, mask=mask)

cv2.imshow('original', img)
cv2.imshow('mask', mask)
cv2.imshow('mask_inv', mask_inv)
cv2.waitKey(0)
cv2.destroyAllWindows()

- Bitwise Not untuk mask hasil thresholding

In [102]:
img = cv2.imread("hand.png")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(gray, 120, 255, cv2.THRESH_BINARY_INV)
mask_inv = cv2.bitwise_not(img, mask=thresh)

cv2.imshow('Bitwise Or', mask_inv)
cv2.imshow('Mask', thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

- Menambahkan trackbar untuk memvariasikan nilai threshold sebelum di apply Bitwise Not

In [104]:
max_value = 255
default_value = 120

title_window = 'Bitwise Not'

def on_trackbar(val):
    ret, thresh = cv2.threshold(gray, val, 255, cv2.THRESH_BINARY_INV)
    mask_inv = cv2.bitwise_not(img, mask=thresh)
    cv2.imshow(title_window, mask_inv)

img = cv2.imread("hand.png")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

cv2.namedWindow(title_window)
cv2.createTrackbar('thresh', title_window , default_value, max_value, on_trackbar)

on_trackbar(default_value)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Bitwise And

- Bitwise And dalam python menggunakan operator `&`
- Misal pixel value 1 = $100_{10} = 01100100_2$, 
- dan pixel value 2 = $40_{10} = 00101000_2$, 
- Jika diterapkan bitwise And pada pixel tersebut, maka akan dihasilkan nilai pixel baru $00100000_2=32_{10}$

```
01100100
00101000
-------- &
00100000
```

In [109]:
a = np.array([100]).astype(np.uint8)
b = np.array([100]).astype(np.uint8)

a & b

array([100], dtype=uint8)

In [106]:
cv2.bitwise_and(a, b)

array([[32]], dtype=uint8)

- Bitwise And untuk mask kotak putih

In [111]:
img1 = cv2.imread("lena.jpg")
img2 = cv2.imread("apple.jpg")
h, w, c = img1.shape

mask = np.zeros((h, w)).astype(np.uint8)
cv2.rectangle(mask, (h//4, w//4), (3*h//4, 3*w//4), (255, 255,  255), -1)

mask_and = cv2.bitwise_and(img2, img2, mask=mask)

cv2.imshow('mask_inv', mask_and)
cv2.imshow('mask', mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

- Bitwise And untuk mask hasil thresholding

In [118]:
img1 = cv2.imread("apple.jpg")
gray = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(gray, 240, 255, cv2.THRESH_BINARY_INV)

img2 = cv2.imread("lena.jpg")
mask_inv = cv2.bitwise_and(img1, img2, mask=thresh)

cv2.imshow('Bitwise Or', mask_inv)
cv2.imshow('Apple mask', thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Bitwise Or

- Bitwise Or dalam python menggunakan operator `&`
- Misal pixel value 1 = $100_{10} = 01100100_2$, 
- dan pixel value 2 = $40_{10} = 00101000_2$, 
- Jika diterapkan bitwise And pada pixel tersebut, maka akan dihasilkan nilai pixel baru $01101100_2=108_{10}$

```
01100100
00101000
-------- |
01101100
```

In [114]:
a = np.array([100]).astype(np.uint8)
b = np.array([40]).astype(np.uint8)

a | b

array([108], dtype=uint8)

In [115]:
cv2.bitwise_or(a, b)

array([[108]], dtype=uint8)

- Bitwise Or untuk mask lingkaran putih

In [119]:
img1 = cv2.imread("lena.jpg")
img2 = cv2.imread("apple.jpg")
h, w, c = img1.shape

mask = np.zeros((h, w)).astype(np.uint8)
cv2.circle(mask, (h//2, w//2), 100, (255, 255,  255), -1)

mask_and = cv2.bitwise_or(img1, img2, mask=mask)

cv2.imshow('mask_inv', mask_and)
cv2.waitKey(0)
cv2.destroyAllWindows()

- Bitwise Or untuk mask hasil thresholding

In [101]:
img1 = cv2.imread("apple.jpg")
gray = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(gray, 240, 255, cv2.THRESH_BINARY_INV)

img2 = cv2.imread("lena.jpg")
mask_inv = cv2.bitwise_or(img2, img2, mask=thresh)

cv2.imshow('Bitwise Or', mask_inv)
cv2.waitKey(0)
cv2.destroyAllWindows()

___

## Range Thresholding

- Image thresholding using `cv2.threshold()` function. <br>
<img src="resource/Binary_Thresh.png" style="width: 500px; margin-top:10px;" > </img>
- Now we will learn how to do **range based thresholding** using  `cv2.inRange()` function. <br>
<img src="resource/Range_Thresh.png" style="width: 500px; margin-top:10px;" > </img>
- The concept remains the same, but now we add a range of pixel values we need.
- Method `cv2.inRange(img, lower_color, upper_color)`
- where theparameter :
    - `img` : input image (HSV color space)
    - `lower_color` : tuple (H, S, V) of lower color 
    - `upper_color` : tuple (H, S, V) of upper color 
- `H, S, V` value range in OpenCV:
    - `H` (0 - 180)
    - `S` (0 - 255)
    - `V` (0 - 255)
- `cv2.inRange()` using **HSV colorspace**, since the **hue channel** models the **color type**, it is very useful in image processing tasks that need to **segment objects based on its color**.<br>
<img src="resource/Threshold_inRange_HSV_colorspace.jpg" style="width: 300px; margin-top:10px;" > </img>
- Since colors in the **RGB colorspace** are coded using the **three channels**, it is **more difficult** to segment an object in the image based on its color.<br>
<img src="resource/Threshold_inRange_RGB_colorspace.jpg" style="width: 300px; margin-top:10px;" > </img>
- **HSV colorspace** model : <br>
<img src="resource/HSV_hue_model.png" style="width: 300px; margin-top:10px;" > </img>

- Conver RGB value to HSV (`cv2.cvtColor()`)

In [122]:
green = np.uint8([[[255,0,0 ]]])
hsv_green = cv2.cvtColor(green, cv2.COLOR_BGR2HSV)
print( hsv_green )

[[[120 255 255]]]


- Detect Red, Green and Blue Color from image

In [126]:
img = cv2.imread('blocks.jpg')

#convert to hsv
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

# define range of blue color in HSV
lower_blue = np.array([110, 50, 50])
upper_blue = np.array([130, 255, 255])

# define range of red color in HSV
lower_red = np.array([-10, 50, 50])
upper_red = np.array([10, 255, 255])

# define range of green color in HSV
lower_green = np.array([50, 50, 50])
upper_green = np.array([70, 255, 255])

# Threshold the HSV image to get only blue colors
mask_blue = cv2.inRange(hsv.copy(), lower_blue, upper_blue)
mask_red = cv2.inRange(hsv.copy(), lower_red, upper_red)
mask_green = cv2.inRange(hsv.copy(), lower_green, upper_green)

mask = mask_blue + mask_red + mask_green

res = cv2.bitwise_and(img, img, mask= mask)

cv2.imshow('frame',img)
cv2.imshow('res',res)
cv2.imshow('mask',mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:

cv2.destroyAllWindows()

### Task
- Input video Detect color yellow

In [15]:
# ---- jawaban ----
#
#
#

In [5]:
# define range of yellow color in HSV
lower_yellow = np.array([25, 50, 50])
upper_yellow = np.array([35, 255, 255])

cap = cv2.VideoCapture("yellow_ball.mp4")

while cap.isOpened():
    ret, frame = cap.read()
    if ret :
        frame = cv2.resize(frame, (0,0), fx=0.5, fy=0.5)
        hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
        mask = cv2.inRange(hsv.copy(), lower_yellow, upper_yellow)
        res = cv2.bitwise_and(frame, frame, mask= mask)
        
        cv2.imshow('Detected Object',res)

        if cv2.waitKey(10) == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()

___

## Shape Detection

### Hough Line Transform (Line Detector)

<img src="resource/lane.gif" style="width:500px, margin-top:10px"></img>
- The Hough Line Transform is a transform used to detect **straight lines**.
- To apply the Transform, first an **edge detection** pre-processing is desirable.
- As you know, a line in the image space can be expressed with two variables. For example:
    - In the **Cartesian** coordinate system: Parameters: ($m$,$b$).
    - In the **Polar** coordinate system: Parameters: ($r$,$θ$). <br>
      <img src="resource/Hough_Lines_Tutorial_Theory_0.jpg" style="width:400px, margin-top:10px"></img>
    - For Hough Transforms, we will express lines in the *Polar system*. Hence, a line equation can be written as: <br>
    $y = \left ( -\dfrac{\cos \theta}{\sin \theta} \right ) x + \left ( \dfrac{r}{\sin \theta} \right )$ <br>
    Arranging the terms: $r = x \cos \theta + y \sin \theta$ <br>
    - In general for each point ($x_{0}, y_{0}$), we can define the family of lines that goes through that point as: <br>
        $r_{\theta} = x_{0} \cdot \cos \theta + y_{0} \cdot \sin \theta$ <br>
        Meaning that each pair ($r_{\theta},\theta$) represents each line that passes by ($x_{0}, y_{0}$).
    - If for a given ($x_{0}, y_{0}$) we plot the family of lines that goes through it, we get a sinusoid. For instance, for $x_{0}$=8 and $y_{0}$=6 we get the following plot (in a plane $θ - r$): <br>
        <img src="resource/Hough_Lines_Tutorial_Theory_1.jpg" style="width:400px, margin-top:10px"></img> <br>
        We consider only points such that $r > 0$ and $0< \theta < 2 \pi$.
    - We can do the same operation above for all the points in an image. If the curves of two different points intersect in the plane $θ - r$, that means that both points belong to a same line. For instance, following with the example above and drawing the plot for two more points: $x_{1}=4, y_{1}=9$ and $x_{2}=12, y_{2}=3$, we get: <br>
        <img src="resource/Hough_Lines_Tutorial_Theory_2.jpg" style="width:400px, margin-top:10px"></img> <br>
        The three plots intersect in one single point (0.925,9.6), these coordinates are the parameters (θ$,r$) or the line in which ($x_{0},y_{0}$), ($x_{1},y_{1}$) and ($x_{2},y_{2}$) lay.
    > A line can be detected by finding the **number of intersections between curves**.The **more curves intersecting** means that the line represented by that **intersection have more points**.
    > In general, we can define a **threshold** of the **minimum number of intersections** needed to **detect a line**.
    > This is what the **Hough Line Transform** does. It keeps track of the intersection between curves of every point in the image. 

#### OpenCV implements two kind of Hough Line Transforms:

- The **Standard Hough Transform** <br>
    It consists in pretty much what we just explained in the previous section. It gives you as result a vector of couples ($θ,rθ$)
    In OpenCV it is implemented with the function `cv2.HoughLines()`.

- The **Probabilistic Hough Line Transform** <br>
    A more efficient implementation of the Hough Line Transform. It gives as output the extremes of the detected lines ($x_{0},y_{0},x_{1},y_{1}$)
    In OpenCV it is implemented with the function `cv2.HoughLinesP()`.

#### Standard Hough Transform `cv2.HoughLines()`

- menggunakan method `cv2.HoughLines(img, rho, theta, threshold, lines, srn, stn)`
- with the following arguments:
    - `img` : input image (edge image)
    - `rho` : The resolution of the parameter r in pixels. We use 1 pixel.
    - `theta` : The resolution of the parameter θ in radians. We use 1 degree (`np.pi/180`)
    - `threshold` : The minimum number of intersections to *detect* a line
    - `lines` : A vector that will store the parameters ($r,θ$) of the detected lines
    - `srn` and `stn` : Default parameters to zero. 

In [20]:
img = cv2.imread('road.jpg')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 50, 200)

lines = cv2.HoughLines(edges, 1, np.pi / 180, 100, None, 0, 0)

In [21]:
for line in lines:
    rho = line[0][0]
    theta = line[0][1]
    a = math.cos(theta)
    b = math.sin(theta)
    x0 = a * rho
    y0 = b * rho
    x1, y1 = (int(x0 + 1000*(-b)), int(y0 + 1000*(a)))
    x2, y2 = (int(x0 - 1000*(-b)), int(y0 - 1000*(a)))
    cv2.line(img, (x1, y1), (x2, y2), (255, 0, 0), 1, cv2.LINE_AA)

cv2.imshow("Hough Line Transform", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

- Trackbar mengatur nilai threshold

In [22]:
max_value = 300
default_value = 150

title_window = "Hough Line Transform"

def on_trackbar(val):
    frame = img.copy()
    lines = cv2.HoughLines(edges, 1, np.pi / 180, val, None, 0, 0)
    if lines is not None:
        for line in lines:
            rho = line[0][0]
            theta = line[0][1]
            a = math.cos(theta)
            b = math.sin(theta)
            x0 = a * rho
            y0 = b * rho
            x1, y1 = (int(x0 + 1000*(-b)), int(y0 + 1000*(a)))
            x2, y2 = (int(x0 - 1000*(-b)), int(y0 - 1000*(a)))
            cv2.line(frame, (x1, y1), (x2, y2), (255, 0, 255), 1, cv2.LINE_AA)

    cv2.imshow(title_window, frame)

img = cv2.imread('road.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 50, 200)

cv2.namedWindow(title_window)
cv2.createTrackbar('thresh', title_window , default_value, max_value, on_trackbar)

on_trackbar(default_value)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### Probabilistic  Hough Transform `cv2.HoughLinesP()`

- menggunakan method `cv2.HoughLinesP(img, rho, theta, threshold, lines, minLinLength, maxLineGap)`
- with the following arguments:
    - `img` : input image (edge image)
    - `rho` : The resolution of the parameter r in pixels. We use 1 pixel.
    - `theta` : The resolution of the parameter θ in radians. We use 1 degree (`np.pi/180`)
    - `threshold` : The minimum number of intersections to *detect* a line
    - `lines` : A vector that will store the parameters ($r,θ$) of the detected lines
    - `minLinLength` : The minimum number of points that can form a line. Lines with less than this number of points are disregarded.
    - `maxLineGap` : The maximum gap between two points to be considered in the same line.

In [33]:
img = cv2.imread('road.jpg')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 50, 200)
lines = cv2.HoughLinesP(edges, 1, np.pi/180, 50, minLineLength=50, maxLineGap=30)

for line in lines:
    x1, y1, x2, y2 = line[0]
    cv2.line(img, (x1, y1), (x2, y2), (0, 255, 0), 2)

cv2.imshow("Result Image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

- Trackbar untuk mengatur `minLinLength` dan `maxLineGap`

In [34]:
maxLineGap = 20
minLineLength = 100

title_window = "Hough Line Transform"

def draw_line(lines):
    frame = img.copy()
    if lines is not None:
        for line in lines:
            x1, y1, x2, y2 = line[0]
            cv2.line(frame, (x1, y1), (x2, y2), (255, 0, 255), 1, cv2.LINE_AA)

    cv2.imshow(title_window, frame)  
    
def on_trackbar_minLineLength(val):
    global minLineLength
    minLineLength = val
    lines = cv2.HoughLinesP(edges, 1, np.pi/180, 50, minLineLength=minLineLength, maxLineGap=maxLineGap)
    draw_line(lines)
    
def on_trackbar_maxLineGap(val):
    global maxLineGap
    maxLineGap = val
    lines = cv2.HoughLinesP(edges, 1, np.pi/180, 50, minLineLength=minLineLength, maxLineGap=maxLineGap)
    draw_line(lines)

img = cv2.imread('road.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 50, 200)

cv2.namedWindow(title_window)
cv2.createTrackbar('maxGap', title_window , 20, 200, on_trackbar_maxLineGap)
cv2.createTrackbar('minLen', title_window , 100, 200, on_trackbar_minLineLength)

on_trackbar_minLineLength(100)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Hough Circle Transform
- The Hough Circle Transform works in a roughly analogous way to the Hough Line Transform explained in the previous tutorial.
- In the line detection case, a line was defined by two parameters ($r,θ$). 
- Parameters to define a circle:
$C : ( x_{center}, y_{center}, r )$
- where ($x_{center},y_{center}$) define the center position (green point) and $r$ is the radius, which allows us to completely define a circle, as it can be seen below:
 <img src="resource/Hough_Circle_Tutorial_Theory_0.jpg" style="width:400px, margin-top:10px"></img>


#### Hough Circle Transform `cv2.HoughCircles()`

- menggunakan method `cv2.HoughCircles(img, mode, dp, min_dist_center, param1, param2, min_radius, max_radius)`
- with the arguments:
    - `img` : input image.
    - `mode` : 
        - `cv2.HOUGH_STANDARD` : Classical or standard Hough transform.
        - `cv2.HOUGH_PROBABILISTIC` : Probabilistic Hough transform (more efficient in case if the picture contains a few long linear segments).
        - `cv2.HOUGH_MULTI_SCALE` : multi-scale variant of the classical Hough transform. 
        - `cv2.HOUGH_GRADIENT`
    - `dp` : The inverse ratio of resolution (default 1).
    - `min_dist_center` : Minimum distance between detected centers.
    - `param1` : Upper threshold for the internal Canny edge detector.
    - `param2` : Threshold for center detection.
    - `min_radius` : Minimum radius to be detected. If unknown, put zero as default.
    - `max_radius` : Maximum radius to be detected. If unknown, put zero as default.

In [38]:
img = cv2.imread('eye.jpg')
h, w, c = img.shape

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

blur = cv2.GaussianBlur(gray,(5,5), 0, 0)

circles = cv2.HoughCircles(blur, cv2.HOUGH_GRADIENT, 1, h/64, param1=200, param2=17, minRadius=21, maxRadius=30)

if circles is not None:
    circles = np.uint16(np.around(circles))[0]
    for i in circles:
        cv2.circle(img, (i[0], i[1]), i[2], (0, 255, 0), 2)

        
cv2.imshow("output", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
minRadius = 21
maxRadius = 30
param1 = 200
param2 = 17

title_window = "Hough Circle Transform"

def draw_circle(circles):
    frame = img.copy()
    if circles is not None:
        circles = np.uint16(np.around(circles))[0]
        for i in circles:
            cv2.circle(frame, (i[0], i[1]), i[2], (0, 255, 255), 2, cv2.LINE_AA)

    cv2.imshow(title_window, frame)  
    
def on_trackbar_minRadius(val):
    global minRadius
    minRadius = val
    circles = cv2.HoughCircles(blur, cv2.HOUGH_GRADIENT, 1, h/64, param1=param1, param2=param2, minRadius=minRadius, maxRadius=maxRadius)
    draw_circle(circles)
    
def on_trackbar_maxRadius(val):
    global maxRadius
    maxRadius = val
    circles = cv2.HoughCircles(blur, cv2.HOUGH_GRADIENT, 1, h/64, param1=param1, param2=param2, minRadius=minRadius, maxRadius=maxRadius)
    draw_circle(circles)
    
def on_trackbar_param1(val):
    global param1
    param1 = val
    circles = cv2.HoughCircles(blur, cv2.HOUGH_GRADIENT, 1, h/64, param1=param1, param2=param2, minRadius=minRadius, maxRadius=maxRadius)
    draw_circle(circles)
    
def on_trackbar_param2(val):
    global param2
    param2 = val
    circles = cv2.HoughCircles(blur, cv2.HOUGH_GRADIENT, 1, h/64, param1=param1, param2=param2, minRadius=minRadius, maxRadius=maxRadius)
    draw_circle(circles)

img = cv2.imread('eye.jpg')
h, w, c = img.shape
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
blur = cv2.GaussianBlur(gray,(5,5), 0, 0)

cv2.namedWindow(title_window)
cv2.createTrackbar('minRadius', title_window , 21, 50, on_trackbar_minRadius)
cv2.createTrackbar('maxRadius', title_window , 30, 50, on_trackbar_maxRadius)
cv2.createTrackbar('param1', title_window , 200, 255, on_trackbar_param1)
cv2.createTrackbar('param2', title_window , 17, 30, on_trackbar_param2)

on_trackbar_minRadius(minRadius)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Task
- Dectect Yellow Ball on video `yellow_bal.mp4` using Hough Circle

In [88]:
# ---- jawaban ----
#
#
#

In [40]:
cap = cv2.VideoCapture("yellow_ball.mp4")

while cap.isOpened():
    ret, frame = cap.read()
    if ret :
        frame = cv2.resize(frame, (0,0), fx=0.5, fy=0.5)
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        circles = cv2.HoughCircles(gray, cv2.HOUGH_GRADIENT, 1, h/2, param1=180, param2=17, minRadius=21, maxRadius=100)

        if circles is not None:
            circles = np.uint16(np.around(circles))[0]
            for i in circles:
                cv2.circle(frame, (i[0], i[1]), i[2], (0, 255, 0), 2)
        
        cv2.imshow('Hough Circle - Video', frame)

        if cv2.waitKey(10) == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()

## Aplication Hough Lines

- Real-tim Road Line Detection <br>
Original Video : [https://www.youtube.com/watch?v=KWJaBJYJIjI](https://www.youtube.com/watch?v=KWJaBJYJIjI)

In [4]:
maxLineGap = 200
minLineLength = 50
title_window = "Road Lane Detector"
poly = [[59, 339], [293, 217], [434, 210], [613, 325]]
is_draw = False

def on_trackbar_minLineLength(val):
    global minLineLength
    minLineLength = val

def on_trackbar_maxLineGap(val):
    global maxLineGap
    maxLineGap = val
    
def read_poly(event,x,y,flags,param):
    global poly, is_draw
    
    if event == cv2.EVENT_RBUTTONDOWN:
        is_draw = True
        poly = []
        
    if event == cv2.EVENT_LBUTTONDOWN and is_draw:
        poly.append([x, y])
    
    if len(poly) == 4 and is_draw:
        is_draw = False
    
cv2.namedWindow(title_window)
cv2.createTrackbar('maxGap', title_window , 200, 400, on_trackbar_maxLineGap)
cv2.createTrackbar('minLen', title_window , 50, 400, on_trackbar_minLineLength)
cv2.setMouseCallback(title_window, read_poly) 

cap = cv2.VideoCapture('drive.mp4')

while cap.isOpened():
    ret, frame = cap.read()
    if ret :
        frame = cv2.resize(frame, (0,0), fx=0.5, fy=0.5)
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        if not is_draw :
            stencil = np.zeros_like(gray)
            polygon = np.array(poly)
            cv2.fillConvexPoly(stencil, polygon, 1)
            roi = cv2.bitwise_and(gray, gray, mask=stencil)

            ret, thresh = cv2.threshold(roi, 130, 255, cv2.THRESH_BINARY)
            cv2.imshow('roi', roi)

            lines = cv2.HoughLinesP(thresh, rho=1, theta=np.pi/180, threshold=20, minLineLength=minLineLength, maxLineGap=maxLineGap)
            if lines is not None:
                for line in lines:
                    x1, y1, x2, y2 = line[0]
                    cv2.line(frame, (x1, y1), (x2, y2), (255, 0, 255), 1, cv2.LINE_AA)

        cv2.imshow(title_window, frame)

        if cv2.waitKey(25) == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()

___
### Real-time Lane Detector

- Dari hasil sebelumnya kita dapat mendeteksi Road Lane dengan menggunakan `cv2.HoughLinesP()`
- Namun banyak `lines` yang terdeteksi disisi kanan maupun  kiri,
<img src="resource/overlay_v1.png" style="width: 500px; margin-top:10px;" > </img> <br>
<img src="resource/slope_intersect.png" style="width: 400px; margin-top:10px;" > </img> <br>
- Rata-ratakan slope ($m$) dan Intersept ($c$), disisi kanan dan kiri,<br>
<img src="resource/slope_intersect_mean.png" style="width: 400px; margin-top:10px;" > </img>
- Setelahnya tentukan ($x_1, y_1$) dan ($x_2, y_2$) sisi kanan dan kiri,<br>
<img src="resource/coordinate.png" style="width: 500px; margin-top:10px;" > </img>
- Tambahkan overlay sebagai berikut dari `lines` yang didapatkan  `cv2.HoughLinesP()` <br>
<img src="resource/overlay.png" style="width: 500px; margin-top:10px;" > </img> 


In [ ]:
title_window = "Road Lane Detector"
roi_poly = np.array([[59, 339], [293, 217], [434, 210], [613, 325]])

cap = cv2.VideoCapture('drive.mp4')

while cap.isOpened():
    ret, frame = cap.read()
    if ret : 
        frame = cv2.resize(frame, (0,0), fx=0.5, fy=0.5)
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        mask = np.zeros(gray.shape).astype(np.uint8)
        cv2.fillPoly(mask, [roi_poly], (255,255,255))
        roi = cv2.bitwise_and(gray, gray, mask=mask)

        ret, thresh = cv2.threshold(roi, 130, 255, cv2.THRESH_BINARY)
        edged = cv2.Canny(thresh, 127, 200)

        lines = cv2.HoughLinesP(edged, 1, np.pi/180, 10, np.array([]), minLineLength=20, maxLineGap=5)

        overlay = draw_lines(edged.shape, lines, thickness=3, scale = 0.65)
        frame = cv2.addWeighted(overlay, 1, frame, 0.8, 0)

        cv2.imshow(title_window, frame)
        cv2.imshow(title_window + "- ROI", roi)
        cv2.imshow(title_window + "- Edge", edged)
        cv2.imshow(title_window + "- thresh", thresh)
        if cv2.waitKey(25) == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()

In [11]:
r_m, l_m, r_c, l_c = [],[],[],[]
def draw_lines(shape, lines, thickness=3, scale = 0.65):
    global r_m, l_m, r_c, l_c
    h, w = shape
    img = np.zeros((h, w, 3), dtype=np.uint8)
    
    if lines is not None :
        for line in lines:
            for x1,y1,x2,y2 in line:
                slope = (y1-y2)/(x1-x2)
                if slope > 0.3:
                    yintercept = y2 - (slope*x2)
                    r_m.append(slope)
                    r_c.append(yintercept)
                elif slope < -0.3:
                    yintercept = y2 - (slope*x2)
                    l_m.append(slope)
                    l_c.append(yintercept)

    avg_l_m = np.mean(l_m[-30:])
    avg_l_c = np.mean(l_c[-30:])
    avg_r_m = np.mean(r_m[-30:])
    avg_r_c = np.mean(r_c[-30:])

    try:
        y1, y2 = int(scale*h), h
        l_x1 = int((y1 - avg_l_c)/avg_l_m)
        l_x2 = int((y2 - avg_l_c)/avg_l_m)
        r_x1 = int((y1- avg_r_c)/avg_r_m)
        r_x2 = int((y2 - avg_r_c)/avg_r_m)
        
        pts = np.array([[l_x1, y1],[l_x2, y2],[r_x2, y2],[r_x1, y1]]).astype(np.int32)
        pts = pts.reshape((-1,1,2))
        cv2.fillPoly(img,[pts],(0,127,50))
        cv2.line(img, (l_x1, y1), (l_x2, y2), (0,255,255), thickness)
        cv2.line(img, (r_x1, y1), (r_x2, y2), (0,255,255), thickness)
        return img
    except ValueError:
        pass
