# **BELAJAR COMPUTER VISION - OpenCV Part 5**

## OpenCV - Part 5

- Region Mask
- Range Thresholding
- Shape Detection (Hough Transform)

In [1]:
%matplotlib inline
import cv2
import numpy as np
import sys
import matplotlib.pyplot as plt
import os
import math

sys.path

['e:\\BELAJAR-PEMROGRAMAN\\Dicky_X_RPL_B\\CODING\\belajar_computer_vision\\belajar_computer_vision\\pertemuan11-opencv',
 'c:\\Users\\Dicky\\AppData\\Local\\Programs\\Python\\Python310\\python310.zip',
 'c:\\Users\\Dicky\\AppData\\Local\\Programs\\Python\\Python310\\DLLs',
 'c:\\Users\\Dicky\\AppData\\Local\\Programs\\Python\\Python310\\lib',
 'c:\\Users\\Dicky\\AppData\\Local\\Programs\\Python\\Python310',
 '',
 'C:\\Users\\Dicky\\AppData\\Roaming\\Python\\Python310\\site-packages',
 'C:\\Users\\Dicky\\AppData\\Roaming\\Python\\Python310\\site-packages\\win32',
 'C:\\Users\\Dicky\\AppData\\Roaming\\Python\\Python310\\site-packages\\win32\\lib',
 'C:\\Users\\Dicky\\AppData\\Roaming\\Python\\Python310\\site-packages\\Pythonwin',
 'c:\\Users\\Dicky\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages']

## Region Mask

- Highly useful while extracting any part of the image, defining and working with **non-rectangular ROI** (region of interest). <br>
  <img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/11.%20OpenCV%20-%20Part%205/resource/sample_mask.png?raw=true" style="width:500px; margin-top:10px"></img>
- Region Mask on image is user **Bitwise Operation** (AND, OR, NOT, and XOR operation).
<img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/11.%20OpenCV%20-%20Part%205/resource/bitwise_operator.jpg?raw=true" style="width:500px; margin-top:10px"></img>
- Method :
    - `cv2.bitwise_not(img1, mask)`
    - `cv2.bitwise_and(img1, img2, mask)`
    - `cv2.bitwise_or(img1, img2, mask)`
    - `cv2.bitwise_xor(img1, img2, mask)`
- with parameter :
    - `img1` : input image 1
    - `img2` : input image 2
    - `mask` : optional operation mask, **8-bit single channel** array, that specifies **elements of the output array to be changed**. <br>
    <img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/11.%20OpenCV%20-%20Part%205/resource/mask_hand.png?raw=true" style="width:200px; margin-top:10px"></img>
    

#### Bitwise Not
- Bitwise not dalam python menggunakan operator `~`
- Misal pixel value $200_{10} = 11001000_2$, 
- Jika diterapkan bitwise not pada pixel tersebut, maka akn dihasilkan nilai pixel baru $00110111_2=55_{10}$

```
11001000
-------- ~
00110111
```

In [3]:
a = np.array([200]).astype(np.uint8)
print(~a)

[55]


In [4]:
cv2.bitwise_not(a)

array([[55]], dtype=uint8)

- Bitwise not untuk mask lingkaran putih

In [5]:
img = cv2.imread('lena.jpg')
h, w, c = img.shape

mask = np.zeros((h ,w)).astype(np.uint8)
cv2.circle(mask, (h//2, w//2), 100, (255,255,255), -1)

mask_inv = cv2.bitwise_not(img, mask=mask)

cv2.imshow('original',img)
cv2.imshow('mask',mask)
cv2.imshow('mask_inv',mask_inv)
cv2.waitKey(0)
cv2.destroyAllWindows()

- Bitwise Not untuk mask hasil thresholding

In [11]:
img = cv2.imread('hand.png')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, thres = cv2.threshold(gray, 120, 255, cv2.THRESH_BINARY_INV)
mask_inv = cv2.bitwise_not(img, mask=thres)

cv2.imshow('mask_inv',mask_inv)
cv2.imshow('mask',thres)
cv2.waitKey(0)
cv2.destroyAllWindows()

- Menambahkan trackbar untuk memvariasikan nilai threshold sebelum di apply Bitwise Not

In [13]:
img = cv2.imread('hand.png')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

max = 255
default = 120

title_window = 'trackbar'

def trackbar(val):
    ret, thres = cv2.threshold(gray, val, max, cv2.THRESH_BINARY_INV)
    mask_inv =  cv2.bitwise_not(img, mask=thres)
    cv2.imshow(title_window, mask_inv)

cv2.namedWindow(title_window)
cv2.createTrackbar('thres',title_window, default, max, trackbar)

trackbar(default)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Bitwise And

- Bitwise And dalam python menggunakan operator `&`
- Misal pixel value 1 = $100_{10} = 01100100_2$, 
- dan pixel value 2 = $40_{10} = 00101000_2$, 
- Jika diterapkan bitwise And pada pixel tersebut, maka akan dihasilkan nilai pixel baru $00100000_2=32_{10}$

```
01100100
00101000
-------- &
00100000
```

In [16]:
a = np.array([100]).astype(np.uint8)
b = np.array([40]).astype(np.uint8)

c = a&b
print(c)

[32]


In [18]:
cv2.bitwise_and(a, b)

array([[32]], dtype=uint8)

- Bitwise AND untuk mask kotak putih

In [21]:
img1 = cv2.imread('lena.jpg')
img2 = cv2.imread('apple.jpg')
h, w, c = img1.shape

mask = np.zeros((h,w)).astype(np.uint8)
cv2.rectangle(mask, (h//4, w//4),(3*h//4, 3*w//4), (255,255,255),-1)

mask_and = cv2.bitwise_and(img2, img2, mask=mask)

cv2.imshow('mask_and',mask_and)
cv2.imshow('mask',mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

- Bitwise AND untukl mask hasil thresholding

In [31]:
img1 = cv2.imread('apple.jpg')
gray = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
ret, thres = cv2.threshold(gray, 240, 255, cv2.THRESH_BINARY_INV)

img2 = cv2.imread('lena.jpg')
mask_inv = cv2.bitwise_and(img1, img2, mask=thres)

cv2.imshow('mask_inv',mask_inv)
cv2.imshow('mask',thres)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Bitwise Or

- Bitwise Or dalam python menggunakan operator `&`
- Misal pixel value 1 = $100_{10} = 01100100_2$, 
- dan pixel value 2 = $40_{10} = 00101000_2$, 
- Jika diterapkan bitwise And pada pixel tersebut, maka akan dihasilkan nilai pixel baru $01101100_2=108_{10}$

```
01100100
00101000
-------- |
01101100
```

In [25]:
a = np.array([100]).astype(np.uint8)
b = np.array([40]).astype(np.uint8)

a | b

array([108], dtype=uint8)

In [26]:
cv2.bitwise_or(a, b)

array([[108]], dtype=uint8)

- Bitwise Or untuk mask lingkaran putih

In [32]:
img1 = cv2.imread('lena.jpg')
img2 = cv2.imread('apple.jpg')
h, w, c = img1.shape

mask = np.zeros((h,w)).astype(np.uint8)
cv2.circle(mask, (h//2, w//2), 100,(255,255,255),-1)

mask_or = cv2.bitwise_or(img1, img2, mask=mask)

cv2.imshow('mask_or',mask_or)
cv2.imshow('mask',mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

- Bitwise OR untuk mask hasikl thresholding

In [33]:
img1 = cv2.imread('apple.jpg')
gray = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
ret, thres = cv2.threshold(gray, 240, 255, cv2.THRESH_BINARY_INV)

img2 = cv2.imread('lena.jpg')
mask_inv = cv2.bitwise_or(img1, img2, mask=thres)

cv2.imshow('mask_inv',mask_inv)
cv2.imshow('mask',thres)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Range Thresholding

- Image thresholding using `cv2.threshold()` function. <br>
<img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/11.%20OpenCV%20-%20Part%205/resource/Binary_Thresh.png?raw=true" style="width: 500px; margin-top:10px;" > </img>
- Now we will learn how to do **range based thresholding** using  `cv2.inRange()` function. <br>
<img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/11.%20OpenCV%20-%20Part%205/resource/Range_Thresh.png?raw=true" style="width: 500px; margin-top:10px;" > </img>
- The concept remains the same, but now we add a range of pixel values we need.
- Method `cv2.inRange(img, lower_color, upper_color)`
- where theparameter :
    - `img` : input image (HSV color space)
    - `lower_color` : tuple (H, S, V) of lower color 
    - `upper_color` : tuple (H, S, V) of upper color 
- `H, S, V` value range in OpenCV:
    - `H` (0 - 180)
    - `S` (0 - 255)
    - `V` (0 - 255)
- `cv2.inRange()` using **HSV colorspace**, since the **hue channel** models the **color type**, it is very useful in image processing tasks that need to **segment objects based on its color**.<br>
<img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/11.%20OpenCV%20-%20Part%205/resource/Threshold_inRange_HSV_colorspace.jpg?raw=true" style="width: 300px; margin-top:10px;" > </img>
- Since colors in the **RGB colorspace** are coded using the **three channels**, it is **more difficult** to segment an object in the image based on its color.<br>
<img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/11.%20OpenCV%20-%20Part%205/resource/Threshold_inRange_RGB_colorspace.jpg?raw=true" style="width: 300px; margin-top:10px;" > </img>
- **HSV colorspace** model : <br>
<img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/11.%20OpenCV%20-%20Part%205/resource/HSV_hue_model.png?raw=true" style="width: 300px; margin-top:10px;" > </img>

- Conver RGB value to HSV (`cv2.cvtColor()`)

In [34]:
color = np.uint8([[[255,0,0]]])
hsv = cv2.cvtColor(color, cv2.COLOR_BGR2HSV)
print(hsv)

[[[120 255 255]]]


- Detected Red, Green, Blue Color from image

In [36]:
img = cv2.imread('blocks.png')

#* convert to hsv
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

#* define range of blue color in HSV
lower_blue = np. array([110,50,50])
upper_blue = np. array([130,255,255])

#* define range of green color in HSV
lower_green = np. array([50,50,50])
upper_green = np. array([70,255,255])

#* define range of red color in HSV
lower_red = np. array([-10,50,50])
upper_red = np. array([10,255,255])

#* threshold the HSV image to get only blue colors
mask_blue = cv2.inRange(hsv.copy(), lower_blue, upper_blue)
mask_green = cv2.inRange(hsv.copy(), lower_green, upper_green)
mask_red = cv2.inRange(hsv.copy(), lower_red, upper_red)

mask = mask_blue + mask_red + mask_green

res = cv2.bitwise_and(img, img, mask=mask)

cv2.imshow('frame',img)
cv2.imshow('res',res)
cv2.imshow('mask',mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Task
- Input video Detect color yellow

In [ ]:

#* ---jawaban---



