# **BELAJAR COMPUTER VISION - OpenCV Part 4**

- OpenCV Drawing Tool
- Contour Detection
- Draw Contour

In [2]:
%matplotlib inline
import cv2
import numpy as np
import sys
import matplotlib.pyplot as plt
import os
import math

sys.path

['e:\\BELAJAR-PEMROGRAMAN\\Dicky_X_RPL_B\\CODING\\belajar_computer_vision\\belajar_computer_vision\\pertemuan10-opencv',
 'c:\\Users\\Dicky\\AppData\\Local\\Programs\\Python\\Python310\\python310.zip',
 'c:\\Users\\Dicky\\AppData\\Local\\Programs\\Python\\Python310\\DLLs',
 'c:\\Users\\Dicky\\AppData\\Local\\Programs\\Python\\Python310\\lib',
 'c:\\Users\\Dicky\\AppData\\Local\\Programs\\Python\\Python310',
 '',
 'C:\\Users\\Dicky\\AppData\\Roaming\\Python\\Python310\\site-packages',
 'C:\\Users\\Dicky\\AppData\\Roaming\\Python\\Python310\\site-packages\\win32',
 'C:\\Users\\Dicky\\AppData\\Roaming\\Python\\Python310\\site-packages\\win32\\lib',
 'C:\\Users\\Dicky\\AppData\\Roaming\\Python\\Python310\\site-packages\\Pythonwin',
 'c:\\Users\\Dicky\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages']

## OpenCV Drawing Tool

- Draw a **line** by using the OpenCV function `cv2.line()`
- Draw an **ellipse** by using the OpenCV function `cv2.ellipse()`
- Draw a **rectangle** by using the OpenCV function `cv2.rectangle()`
- Draw a **circle** by using the OpenCV function `cv2.circle()`
- Draw a **filled polygon** by using the OpenCV function `cv2.fillPoly()`
- Write a **text** by using the OpenCV function `cv2.putText()`

#### Draw Line (`cv2.line()`)

- Menggunakan method `cv2.line(img, (x0,y0), (xt,yt), (B, G, R), thickness, line_type)` 
- untuk :
    - `img` : input image
    - `(x0, y0)` : start point (tuple)
    - `(xt, yt)` : end point (tuple)
    - `(B, G, R)` : line color (tuple)
    - `thickness` : line thickness 
    - `line_type` :
        - `cv2.FILLED` : filled line
        - `cv2.LINE_4` : 4-connected line
        - `cv2.LINE_8` : 8-connected line
        - `cv2.LINE_AA` : antialiased line

In [2]:
background = np.zeros((400, 400, 3)).astype(np.uint8)

#* horizontal line (red), y0 = yt
cv2.line(background, (100, 350), (300, 350), (50,0,255),3,cv2.FILLED)

#* vertical line (green), x0, = xt
cv2.line(background, (50, 100), (50, 300), (25,255,0),9,cv2.LINE_8)

#* garis miring line (pink)
cv2.line(background, (250, 300), (230, 100), (255,0,255),5,cv2.LINE_4)

#* garis miring line (tosca)
cv2.line(background, (300, 300), (280, 100), (100,127,0),5,cv2.LINE_AA)

cv2.imshow("background", background)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### Draw Rectangle (`cv2.rectangle()`)


- Menggunakan method `cv2.rectangle(img, (x0,y0), (xt,yt), (B, G, R), thickness, line_type)` 
- untuk :
    - `img` : input image
    - `(x0, y0)` : top-left-corner rectangle point (tuple)
    - `(xt, yt)` : bottom-right-corner rectangle point (tuple)
    - `(B, G, R)` : rectangle color (tuple)
    - `thickness` : rectangle thickness (if negative, color will be user as fillcolor)
    - `line_type` :
        - `cv2.FILLED` : filled line
        - `cv2.LINE_4` : 4-connected line
        - `cv2.LINE_8` : 8-connected line
        - `cv2.LINE_AA` : antialiased line

In [3]:
background = np.zeros((400, 400, 3)).astype(np.uint8)

#* outline color
cv2.rectangle(background, (15, 25), (200,150), (0,0,255), 5)

#* fill color
cv2.rectangle(background, (210, 50), (270,270), (0,200,255), -1)

cv2.imshow('background', background)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### Draw Circle (`cv2.circle()`)


- Menggunakan method `cv2.circle(img, (x,y), radius, (B, G, R), thickness, line_type)` 
- untuk :
    - `img` : input image
    - `(x, y)` : circle center point (tuple)
    - `radius` : circle radius (in pixel)
    - `(B, G, R)` : circle color (tuple)
    - `thickness` : circle thickness  (if negative, color will be user as fillcolor)
    - `line_type` :
        - `cv2.FILLED` : filled line
        - `cv2.LINE_4` : 4-connected line
        - `cv2.LINE_8` : 8-connected line
        - `cv2.LINE_AA` : antialiased line

In [7]:
img = cv2.imread('lena.jpg')

#* circle outline
cv2.circle(img,(65,65),55,(0,255,150),2,cv2.LINE_AA)

#* circle fil
cv2.circle(img,(65,250),55,(0,50,250),-1,cv2.LINE_AA)


cv2.imshow('lena.jpg',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### Write Text (`cv2.putText()`)


- Menggunakan method `cv2.putText(img, text, (x,y), font_type, font_scale, (B, G, R), thickness, line_type)` 
- untuk :
    - `img` : input image
    - `text` : string to write in image 
    - `(x, y)` : start-left position of text (tuple)
    - `font_type` : 
        - `cv2.FONT_HERSHEY_SIMPLEX` : size sans-serif font
        - `cv2.FONT_HERSHEY_PLAIN` : small size sans-serif font
        - `cv2.FONT_HERSHEY_DUPLEX` : normal size sans-serif font (more complex than FONT_HERSHEY_SIMPLEX)
        - `cv2.FONT_HERSHEY_COMPLEX` : normal size serif font
        - `cv2.FONT_HERSHEY_TRIPLEX` : normal size serif font (more complex than FONT_HERSHEY_COMPLEX)
        - `cv2.FONT_HERSHEY_COMPLEX_SMALL` : smaller version of FONT_HERSHEY_COMPLEX
        - `cv2.FONT_HERSHEY_SCRIPT_SIMPLEX` : hand-writing style font
        - `cv2.FONT_HERSHEY_SCRIPT_COMPLEX` : more complex variant of FONT_HERSHEY_SCRIPT_SIMPLEX
        - `cv2.FONT_ITALIC` : flag for italic font
    - `(B, G, R)` : circle color (tuple)
    - `thickness` : circle thickness  (if negative, color will be user as fillcolor)
    - `line_type` :
        - `cv2.FILLED` : filled line
        - `cv2.LINE_4` : 4-connected line
        - `cv2.LINE_8` : 8-connected line
        - `cv2.LINE_AA` : antialiased line

In [8]:
A = [1,2,3,4]
B = ['A', 'B','C','D']

C = zip(A, B)
print(list(C))

[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')]


In [10]:
background = np.zeros((200, 600, 3)).astype(np.uint8)
h, w, c = background.shape

font_types = [
    cv2.FONT_HERSHEY_SIMPLEX,
    cv2.FONT_HERSHEY_PLAIN,
    cv2.FONT_HERSHEY_DUPLEX,   
    cv2.FONT_HERSHEY_COMPLEX,
    cv2.FONT_HERSHEY_TRIPLEX,
    cv2.FONT_HERSHEY_COMPLEX_SMALL,
    cv2.FONT_HERSHEY_SCRIPT_SIMPLEX,
    cv2.FONT_HERSHEY_SCRIPT_COMPLEX,
    cv2.FONT_ITALIC
]

texts = [
    'FONT HERSHEY SIMPLEX',
    'FONT HERSHEY PLAIN',
    'FONT HERSHEY DUPLEX',
    'FONT HERSHEY COMPLEX',
    'FONT HERSHEY TRIPLEX',
    'FONT HERSHEY COMPLEX SMALL',
    'FONT HERSHEY SCRIPT SIMPLEX',
    'FONT HERSHEY SCRIPT COMPLEX'
    'FONT ITALIC'
]

for text, font_type in zip(texts, font_types):
    frame = background.copy()
    cv2.putText(frame, text,(50,50),font_type,0.9,(0,255,127),1,cv2.LINE_AA)
    cv2.imshow('Text',frame)
    cv2.waitKey(1000)

cv2.destroyAllWindows()

- Mouse Event Click untuk draw line

In [19]:
x0,y0,xt,yt = 0,0,0,0

title_window = 'draw line'
is_draw = False
frame = np.ones((400,400,3)).astype(np.uint8)*255

def draw_line(x0, y0, xt, yt):
    background = frame.copy()
    cv2.line(background, (x0, y0),(xt,yt), (255,0,255), 15, cv2.LINE_AA)
    cv2.imshow(title_window,background)

def read_line(event,x,y,flags,param):
    global is_draw , x0, y0, xt, yt

    if event == cv2.EVENT_LBUTTONDOWN:
        x0, y0, xt, yt =  x,y,x,y
        is_draw = True

    elif event == cv2.EVENT_MOUSEMOVE:
        xt,yt = x,y

    elif event == cv2.EVENT_LBUTTONUP:
        xt, yt = x,y
        is_draw = False
        
    if is_draw:
        draw_line(x0, y0,xt,yt)

cv2.namedWindow(title_window)
cv2.setMouseCallback(title_window, read_line)
draw_line(x0, y0,xt,yt)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
cv2.destroyAllWindows()

- Mouse Event Click dan Trackbar untuk draw circle

hitung radius circle dengan menggunakan, 

$r = \sqrt{(x - x0)^{2} + (y - y0)^{2}} $ 

untuk $x0$ dan $y0$ merupakan pusat lingkaran.

In [21]:
x0, y0, r = 0,0,0

title_window = 'Draw Circle'
is_draw = False
frmae = np.ones((400, 400, 3)).astype(np.uint8)*255

def draw_circle(x0,y0,r):
    background = frame.copy()
    cv2.circle(background, (x0,y0), r, (0,255,150), 2, cv2.LINE_AA)
    cv2.imshow(title_window, background)

def read_circle(event, x,y,flags,param):

    global x0, y0, r, is_draw

    if event == cv2.EVENT_LBUTTONDOWN:
        x0,y0  = x,y
        is_draw = True

    elif event == cv2.EVENT_MOUSEMOVE:
        r = int(math.sqrt((x - x0)**2 + (y - y0)**2))

    elif event == cv2.EVENT_LBUTTONUP:
        r = int(math.sqrt((x - x0)**2 + (y - y0)**2))
        is_draw = False

    if is_draw:
        draw_circle(x0,y0,r)

cv2.namedWindow(title_window)
cv2.setMouseCallback(title_window, read_circle)

draw_circle(x0, y0, r)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### Task
- Mouse Event Click untuk draw rectangle

In [22]:
x0, y0, xt, yt = 0,0,0,0

title_window = 'Draw Rectangle'
is_draw = False
frmae = np.ones((400, 400, 3)).astype(np.uint8)*255

def draw_rectangle(x0,y0,xt,yt):
    background = frame.copy()
    cv2.rectangle(background, (x0,y0), (xt, yt), (0,200,255), -1, cv2.LINE_AA)
    cv2.imshow(title_window, background)

def read_rectangle(event, x,y,flags,param):

    global x0, y0, xt, yt, is_draw

    if event == cv2.EVENT_LBUTTONDOWN:
        x0,y0,xt,yt  = x,y,x,y
        is_draw = True

    elif event == cv2.EVENT_MOUSEMOVE:
        xt, yt = x,y

    elif event == cv2.EVENT_LBUTTONUP:
        xt, yt = x,y
        is_draw = False

    if is_draw:
        draw_rectangle(x0,y0,xt,yt)

cv2.namedWindow(title_window)
cv2.setMouseCallback(title_window, read_rectangle)

draw_rectangle(x0, y0, xt, yt)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
cv2.destroyAllWindows()

## Contour Detection & Contour Drawing 

- Menggunakan method `cv2.findContour(img, mode, method)`
- dimana :
    - `img` : input image
    - `mode` :
        - `cv2.CHAIN_APPROX_NONE` : all the boundary points are stored
        - `cv2.CHAIN_APPROX_SIMPLE` : only end points / corner of that shape are stored <br>
        <img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/10.%20OpenCV%20-%20Part%204/resource/mode_find_contour.png?raw=true" style="width:300px; margin-top:10px"></img>
        - `with cv2.CHAIN_APPROX_NONE` (734 points) 
        - second image shows the one with `cv2.CHAIN_APPROX_SIMPLE` (only 4 points)
    - `method` : 
        - `cv2.RETR_EXTERNAL`  : retrieves only the **extreme outer contours**.  It sets all contours to `hierarchy[i][2] = hierarchy[i][3] = -1`.
        - `cv2.RETR_LIST`   : retrieves **all of the contours** without establishing any hierarchical relationships. 
        - `cv2.RETR_CCOMP`  : retrieves **all of the contours** and organizes them into a **two-level hierarchy**.  
        - `cv2.RETR_TREE`   : retrieves **all of the contours** and reconstructs a **full hierarchy** of nested contours. 
        
- Output : 
    - `contours` : list of countour location (x,y) : <br>
    <img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/10.%20OpenCV%20-%20Part%204/resource/hierarchy_moves.gif?raw=true" style="width:400px; margin-top:10px"></img>
    
    - `hierarchy` : list of `[Next, Previous, First_Child, Parent]`, <br> Representation of this relationship when some shapes are inside other shapes, we call outer one as **parent** and inner one as **child**. 
        - `Next` : next contour at the same hierarchical level.
        - `Previous` : previous contour at the same hierarchical level.
        - `First_Child` : first child contour.
        - `Parent` : index of its parent contour. <br>
        > *If there is no **child** or **parent**, that field is taken as -1*
        - Example :<br>
            <img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/10.%20OpenCV%20-%20Part%204/resource/hierarchy.png?raw=true" style="width:400px; margin-top:10px"></img>
            - `Next` & `Previous` :
                - Start from contour-0. Who is next contour in its same level ? It is contour-1. 
                - So simply put Next = 1. Similarly for Contour-1, next is contour-2. So Next = 2. 
                - What about contour-2? There is no next contour in the same level. 
                - So simply, put Next = -1. 
                - What about contour-4? It is in same level with contour-5. 
                - So its next contour is contour-5, so Next = 5.
            - `First_Child` & `Parent` :
                - For contour-2, child is contour-2a. 
                - So it gets the corresponding index value of contour-2a. 
                - What about contour-3a? It has two children. 
                - But we take only first child. And it is contour-4. So First_Child = 4 for contour-3a.

#### Method `cv2.RETR_EXTERNAL`
- retrieves only the extreme outer contours. It sets all contours to hierarchy[i][2] = hierarchy[i][3] = -1.

In [32]:
img = cv2.imread('hierarchy2.png')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

ret, thres = cv2.threshold(gray,127,255,cv2.THRESH_BINARY)

contours, hierarchy = cv2.findContours(thres, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

In [33]:
hierarchy 

array([[[ 1, -1, -1, -1],
        [ 2,  0, -1, -1],
        [-1,  1, -1, -1]]], dtype=int32)

### Draw Contour `cv2.drawContour()`

- menggunakan method `cv2.drawContours(img, contour, contour_index, (B,G,R), thickness)`
- dimana :
    - `img` : input image
    - `contour` : contour location (list)
    - `contour_index` : parameter indicating a contour to draw. If it is negative, all the contours are drawn.
    - `(B,G,R)` : contour color
    - `thickness` : contour thickness

In [34]:
contours

(array([[[ 56, 171]],
 
        [[ 56, 172]],
 
        [[ 56, 173]],
 
        ...,
 
        [[ 59, 171]],
 
        [[ 58, 171]],
 
        [[ 57, 171]]], dtype=int32),
 array([[[289,  74]],
 
        [[289,  75]],
 
        [[289,  76]],
 
        ...,
 
        [[292,  74]],
 
        [[291,  74]],
 
        [[290,  74]]], dtype=int32),
 array([[[ 69,  39]],
 
        [[ 69,  40]],
 
        [[ 69,  41]],
 
        [[ 69,  42]],
 
        [[ 69,  43]],
 
        [[ 69,  44]],
 
        [[ 69,  45]],
 
        [[ 69,  46]],
 
        [[ 69,  47]],
 
        [[ 69,  48]],
 
        [[ 69,  49]],
 
        [[ 69,  50]],
 
        [[ 69,  51]],
 
        [[ 70,  51]],
 
        [[ 71,  51]],
 
        [[ 72,  51]],
 
        [[ 73,  51]],
 
        [[ 74,  51]],
 
        [[ 75,  51]],
 
        [[ 76,  51]],
 
        [[ 77,  51]],
 
        [[ 78,  51]],
 
        [[ 79,  51]],
 
        [[ 80,  51]],
 
        [[ 81,  51]],
 
        [[ 82,  51]],
 
        [[ 83,  51]],
 
        

In [35]:
for cnt in contours:
    cv2.drawContours(img, cnt, -1, (0,0,255), 3)

cv2.imshow('contours' ,img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Method `cv2.RETR_TREE`
- retrieves **all of the contours** and reconstructs a **full hierarchy** of nested contours. <br>
<img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/10.%20OpenCV%20-%20Part%204/resource/tree_hierarchy.png?raw=true" style="width:450px; margin-top:10px;"></img>

In [45]:
img = cv2.imread('hierarchy2.png')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

ret, thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)

contours, hierarchy = cv2.findContours(thres, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)

In [46]:
hierarchy

array([[[ 7, -1,  1, -1],
        [-1, -1,  2,  0],
        [-1, -1,  3,  1],
        [-1, -1,  4,  2],
        [-1, -1,  5,  3],
        [ 6, -1, -1,  4],
        [-1,  5, -1,  4],
        [ 8,  0, -1, -1],
        [-1,  7, -1, -1]]], dtype=int32)

In [47]:
for cnt in contours:
    cv2.drawContours(img, cnt, -1, (0,0,255), 3)

cv2.imshow('contours' ,img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Method `cv2.RETR_CCOMP`
- retrieves **all of the contours** and organizes them into a **two-level hierarchy**. <br>
<img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/10.%20OpenCV%20-%20Part%204/resource/ccomp_hierarchy.png?raw=true" style="width:450px; margin-top:10px;"></img>

In [48]:
img = cv2.imread('hierarchy2.png')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

ret, thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)

contours, hierarchy = cv2.findContours(thres, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)

In [49]:
hierarchy

array([[[ 3, -1,  1, -1],
        [ 2, -1, -1,  0],
        [-1,  1, -1,  0],
        [ 5,  0,  4, -1],
        [-1, -1, -1,  3],
        [ 7,  3,  6, -1],
        [-1, -1, -1,  5],
        [ 8,  5, -1, -1],
        [-1,  7, -1, -1]]], dtype=int32)

In [51]:
for cnt in contours:
    cv2.drawContours(img, cnt, -1, (0,0,255), 3)

cv2.imshow('contours' ,img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Task

- Read `noisy_text.png`
- Convert to grayscale
- Apply thresholding, 
- Find extream contour 
- Draw contour

![](https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/10.%20OpenCV%20-%20Part%204/resource/jawaban_task2.PNG?raw=true)

In [56]:
img = cv2.imread('noisy_text.png')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

ret, threshold = cv2.threshold(gray, 100, 255, cv2.THRESH_BINARY_INV)

contours, hierarchy = cv2.findContours(threshold, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

for cnt in contours:
    cv2.drawContours(img, cnt, -1, (255,0,255), 6)

cv2.imshow('noisy',img)
cv2.imshow('Binary',threshold)
cv2.waitKey(0)
cv2.destroyAllWindows()

____
## Contour Feature 
- Contour Area (luasan) <br>
    `area = cv2.contourArea(cnt)`
- Contour Perimeter (keliling) <br>
    `perimeter = cv2.arcLength(cnt,True)`
- Contour Approximation <br>
    `epsilon = 0.1*cv2.arcLength(cnt,True)` <br>
    `approx = cv2.approxPolyDP(cnt,epsilon,True)` <br>
    Below, in second image, green line shows the approximated curve for epsilon = 10% of arc length. <br>
    Third image shows the same for epsilon = 1% of the arc length. <br>
    <img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/10.%20OpenCV%20-%20Part%204/resource/approx.jpg?raw=true" style="width:400px; margin-top:10px;"></img>
- Convex Hull <br>
    `hull = cv2.convexHull(points[, hull[, clockwise[, returnPoints]]` <br>
    <img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/10.%20OpenCV%20-%20Part%204/resource/convexitydefects.jpg?raw=true" style="width:200px; margin-top:10px;"></img>
- Bounding Rectangle <br>
    <img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/10.%20OpenCV%20-%20Part%204/resource/boundingrect.png?raw=true" style="width:200px; margin-top:10px;"></img>
    - Straight Bounding Rectangle <br>
        `rect = cv2.boundingRect(cc)`
    - Rotated Rectangle <br>
        `rect = cv2.minAreaRect(cnt)`
- Minimum Enclosing Circle <br>
    `(x,y),radius = cv2.minEnclosingCircle(cnt)` <br>
    `center = (int(x),int(y))` <br>
    `radius = int(radius)` <br>
    <img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/10.%20OpenCV%20-%20Part%204/resource/circumcircle.png?raw=true" style="width:200px; margin-top:10px;"></img>
- Fitting an Ellipse <br>
    `ellipse = cv2.fitEllipse(cnt)` <br>
    `cv2.ellipse(img,ellipse,(0,255,0),2)` <br>
    <img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/10.%20OpenCV%20-%20Part%204/resource/fitellipse.png?raw=true" style="width:200px; margin-top:10px;"></img>
- Fitting a Line <br>
    `rows,cols = img.shape[:2]` <br>
    `[vx,vy,x,y] = cv2.fitLine(cnt, cv2.DIST_L2,0,0.01,0.01)` <br>
    `lefty = int((-x*vy/vx) + y)` <br>
    `righty = int(((cols-x)*vy/vx)+y)` <br>
    <img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/10.%20OpenCV%20-%20Part%204/resource/fitline.jpg?raw=true" style="width:200px; margin-top:10px;"></img>

- Contour Area (luas)

In [57]:
contours

(array([[[1003,  212]],
 
        [[1003,  213]],
 
        [[1004,  214]],
 
        ...,
 
        [[1006,  212]],
 
        [[1005,  212]],
 
        [[1004,  212]]], dtype=int32),
 array([[[847, 212]],
 
        [[848, 213]],
 
        [[849, 214]],
 
        ...,
 
        [[850, 212]],
 
        [[849, 212]],
 
        [[848, 212]]], dtype=int32),
 array([[[666, 212]],
 
        [[666, 213]],
 
        [[666, 214]],
 
        ...,
 
        [[669, 212]],
 
        [[668, 212]],
 
        [[667, 212]]], dtype=int32),
 array([[[101, 212]],
 
        [[101, 213]],
 
        [[101, 214]],
 
        [[101, 215]],
 
        [[101, 216]],
 
        [[101, 217]],
 
        [[101, 218]],
 
        [[101, 219]],
 
        [[101, 220]],
 
        [[101, 221]],
 
        [[101, 222]],
 
        [[101, 223]],
 
        [[101, 224]],
 
        [[101, 225]],
 
        [[101, 226]],
 
        [[101, 227]],
 
        [[101, 228]],
 
        [[101, 229]],
 
        [[101, 230]],
 
        [[101, 2

In [58]:
for cnt in contours:
    area = cv2.contourArea(cnt)
    print(f"luas: {area} pixel")

luas: 12111.0 pixel
luas: 12104.5 pixel
luas: 10484.0 pixel
luas: 16998.5 pixel
luas: 9304.0 pixel
luas: 10492.0 pixel
luas: 7052.0 pixel


- Contour Perimeter (keliling)

In [59]:
for cnt in contours:
    perimeter = cv2.arcLength(cnt,True)
    print(f"keliling: {perimeter} pixel")

keliling: 775.7787802219391 pixel
keliling: 776.3645666837692 pixel
keliling: 782.2741661071777 pixel
keliling: 505.5807341337204 pixel
keliling: 723.4701242446899 pixel
keliling: 722.8427076339722 pixel
keliling: 459.1959581375122 pixel


- Contour Approximation

In [63]:
img = cv2.imread('noisy_text.png')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

ret, threshold = cv2.threshold(gray, 100, 255, cv2.THRESH_BINARY_INV)

contours, hierarchy = cv2.findContours(threshold, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

for cnt in contours:
    epsilon = 0.001 * cv2.arcLength(cnt,True)
    approx = cv2.approxPolyDP(cnt, epsilon, True)
    cv2.polylines(img, [approx], True, (0, 255,255), 3)

cv2.imshow('noisy',img)
# cv2.imshow('Binary',threshold)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
max = 1000
default = 10

title_window = 'Contour Tracbar'

def trackbar(val):
    if val > 0:
        frame = img.copy()
        for cnt in contours:
            epsilon = (1/val)*cv2.arcLength(cnt,True)
            approx = cv2.approxPolyDP(cnt,epsilon,True)
            cv2.polylines(frame, [approx], True, (0, 255, 255), 3)
            cv2.imshow(title_window, frame)

img = cv2.imread('noisy_text.png')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
ret, thresh =cv2.threshold(gray, 100, 255, cv2.THRESH_BINARY_INV)
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

cv2.namedWindow(title_window)
cv2.createTrackbar('divisor', title_window, default, max, trackbar)

trackbar(default)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [65]:
cv2.destroyAllWindows()

- Straight Bounding Rectangle

In [6]:
img = cv2.imread('noisy_text.png')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(gray, 100, 255, cv2.THRESH_BINARY_INV)

contours, hierarchy = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

for cnt in contours:
    rect = cv2.boundingRect(cnt)
    print(rect) #* x, y, w, h

(998, 212, 155, 143)
(843, 212, 154, 143)
(648, 212, 119, 145)
(101, 212, 132, 143)
(515, 210, 118, 147)
(380, 209, 119, 146)
(258, 209, 82, 146)


In [7]:
frame = img.copy()

for cnt in contours:
    rect = cv2.boundingRect(cnt)
    x, y, w, h = rect
    cv2.rectangle(frame, (x, y), (x+w, h+y), (0,0,255), 3)

cv2.imshow("frame", frame)
cv2.waitKey(0)
cv2.destroyAllWindows()

- Crop each contour from input image and display

In [8]:
frame = img.copy()

for i, cnt in enumerate(contours):
    rect = cv2.boundingRect(cnt)
    x, y, w, h = rect
    roi = frame[y:y+h, x:x+w]
    cv2.rectangle(frame, (x, y), (x+w, h+y), (0,0,255), 3)
    cv2.imshow(f"frame {i}", roi)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
frame = img.copy()
roi = []

for i, cnt in enumerate(contours):
    rect = cv2.boundingRect(cnt)
    x, y, w, h = rect
    roi.append(frame[y:y+h, x:x+w])

cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
for i, item in enumerate(roi):
    cv2.imshow(f'image roi {i}', item)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Crop Foto KTP
- Crop foto dari KTP berikut `ktp.jpg` <br>
<img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/10.%20OpenCV%20-%20Part%204/ktp1.jpg?raw=true" style="width:300px; margin-top:10px;"></img>

In [21]:
img = cv2.imread('ktp2.jpg')
h_img, w_img, c = img.shape

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
thresh, binary = cv2.threshold(gray,127,255,cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

contours, hierarchy = cv2.findContours(binary, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)

for cnt in contours:
    rect = cv2.boundingRect(cnt)
    x, y, w, h = rect

    aspectRatio = w/h
    heightRatio = h/h_img

    keepAspectRatio = aspectRatio > 0.7 and aspectRatio < 0.9
    keepHeightRatio = heightRatio > 0.4 and heightRatio < 0.5

    if keepAspectRatio and keepHeightRatio:
        roi = img[y:y+h, x:x+w]
        cv2.rectangle(img, (x,y), (x+w, y+h), (255,0,255), 2)

        cv2.imshow('Binary', binary)
        cv2.imshow('Cropped', roi)

cv2.imshow('Detected', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Pekerjaan Rumah
Crop character plat nomor dari gambar `plat-nomor-1.jpg`

<img src="https://github.com/Muhammad-Yunus/Belajar-Computer-Vision/blob/master/10.%20OpenCV%20-%20Part%204/resource/plat_nomor_crop.png?raw=true" style="width:700px; margin-top:10px;"></img>

In [5]:

#* --jawaban--

img = cv2.imread('plat-nomor-2.jpg')

ratio = 350.0/img.shape[0]
img = cv2.resize(img, (0,0), fx=ratio, fy=ratio)
h_img, w_img, c = img.shape

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

thres, binary_tzr = cv2.threshold(gray, 0, 255, cv2.THRESH_TOZERO + cv2.THRESH_OTSU)
thres, binary = cv2.threshold(binary_tzr, 127, 255,cv2.THRESH_BINARY)

contours, hierarchy = cv2.findContours(binary, cv2.RETR_CCOMP,cv2.CHAIN_APPROX_NONE)

for i, cnt in enumerate(contours):
    area = cv2.contourArea(cnt)
    rect = cv2.boundingRect(cnt)
    x,y,w,h = rect

    aspectRatio = w/h
    heightRatio = h/h_img
    Next,Previos,Firs_Child,Parent = hierarchy[0][i]

    keepAspectRatio = aspectRatio > 0.2 and aspectRatio < 0.7
    keepHeightRatio = heightRatio > 0.25 and heightRatio < 0.5

    if area < 5.0 or w < 3.0 or h < 3.0:
        continue
    if keepAspectRatio and keepHeightRatio and Parent == -1 and Next != -1 and Previos != -1:
        roi = img[y:y+h, x:x+w].copy()
        cv2.rectangle(img, (x,y), (x+w, y+h), (255, 0,255), 2)

        cv2.imshow(f'Cropped {i}', roi)
        cv2.imshow(f'Binary', binary)
        cv2.imshow(f'Detected', img)

cv2.waitKey(0)
cv2.destroyAllWindows()